Enable OBJC and OBJCXX for apple build
Without this small changes build on macOS fails with error like:
```
error: Objective-C was disabled in PCH file but is currently enabled
```

It enables languages `OBJC` and `OBJCXX` when `cmake >= 3.16.0` because
CMake-3.16.0 was the first one which is supported `OBJC` and `OBJCXX`:
https://discourse.cmake.org/t/cmake-3-16-0-available-for-download/262